image: node:14-stretch

stages:
  - Install
  - Build and test
  - Integration test
  - Deploy

variables:
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn/cache
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/cache/Cypress

Yarn install:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - .yarn	
      - cache/Cypress	
      - node_modules/	
      - packages/*/node_modules	
      - yarn.lock	
  stage: Install
  script:
    - yarn install
  artifacts:
    paths:
      - .yarn
      - cache/Cypress
      - node_modules/
      - packages/*/node_modules
      - yarn.lock

Lint:
  stage: Build and test
  dependencies:
    - Yarn install
  script:
    - yarn lint

Unit tests:
  stage: Build and test

  dependencies:
    - Yarn install

  script:
    - yarn test
    - mkdir public
    - cp -r coverage/lcov-report/* public/

  coverage: /All files\s*\|\s*([\d\.]+)/
  artifacts:
    paths:
      - public
    reports:
      junit: junit.xml

Build:
  stage: Build and test
  dependencies:
    - Yarn install
  script:
    - yarn build:prod

  artifacts:
    paths:
      - packages/backend/dist
      - packages/frontend/dist

Cypress:
  image: cypress/base:14.0.0
  stage: Integration test
  dependencies:
    - Yarn install
    - Build
  script:
    - cd packages/testing
    - yarn run:app & yarn test:cypress
  artifacts:
    reports:
      junit: packages/testing/test-results.xml
    paths:
      - packages/testing/videos
      - packages/testing/screenshots

Deploy:
  environment:
    name: test
    url: http://3.233.7.98/app

  dependencies:
    - Yarn install
    - Build
  image: benwainwright/node14-with-yarn-and-aws-cli:latest
  stage: Deploy
  script:
    - yarn workspace @planv7/deployment cdk deploy --require-approval never
    - yarn workspace @planv7/deployment deploy:app

