image: node:14-stretch

stages:
  - Install
  - Build and test
  - Integration test
  - Deploy

variables:
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn/cache
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/cache/Cypress

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .yarn
    - cache/Cypress
    - node_modules/
    - yarn.lock

before_script:
  - yarn install

install:
  stage: Install
  script:
    - yarn install

unit-tests:
  stage: Build and test
  script:
    - yarn lint
    - yarn test
    - mkdir public
    - cp -r coverage/lcov-report/* public/

  coverage: /All files\s*\|\s*([\d\.]+)/
  artifacts:
    paths:
      - public
    reports:
      junit: junit.xml

build:
  stage: Build and test
  script:
    - yarn build:prod

  artifacts:
    paths:
      - packages/backend/dist
      - packages/frontend/dist

cypress:
  stage: Integration test
  script:
    - cd packages/testing
    - yarn run:app & yarn test:cypress
  artifacts:
    reports:
      junit: packages/testing/test-results.xml

# deploy:
#   stage: Deploy
#   script:
#     - yarn workspace @planv7/infrastructure cdk deploy --require-approval never

 
