image: node:14-stretch

stages:
  - install
  - test

variables:
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn/cache
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/cache/Cypress

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .yarn
    - cache/Cypress
    - node_modules/
    - yarn.lock

before_script:
  - yarn install

install:
  stage: install
  script:
    - yarn install

jest:
  stage: test
  script:
    - yarn lint
    - yarn test
    - mkdir public
    - cp -r coverage/lcov-report/* public/

  coverage: /All files\s*\|\s*([\d\.]+)/
  artifacts:
    paths:
      - public
    reports:
      junit: junit.xml
