image: node:14-stretch

stages:
  - Install
  - Build and test
  - Integration test
  - Deploy

variables:
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn/cache
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/cache/Cypress

Get secrets:
  image: benwainwright/node14-with-yarn-and-aws-cli:latest
  stage: Install
  script:
    - echo "JWT_PUBLIC_KEY=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id choirpractise/JAVASCRIPT_WEB_TOKEN_PUBLIC_KEY | jq --raw-output .SecretString)" >> build.env
    - echo "JWT_PRIVATE_KEY=$(aws secretsmanager get-secret-value --region us-east-1 --secret-id choirpractise/JAVASCRIPT_WEB_TOKEN_PRIVATE_KEY | jq --raw-output .SecretString)" >> build.env
  artifacts:
    reports:
      dotenv: build.env

Yarn install:
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    policy: pull-push
    paths:
      - .yarn
      - cache/Cypress
      - node_modules/
      - packages/*/node_modulesk
      - yarn.lock
  stage: Install
  script:
    - yarn install
  artifacts:
    paths:
      - .yarn
      - cache/Cypress
      - node_modules/
      - packages/*/node_modules
      - yarn.lock

Lint:
  stage: Build and test
  dependencies:
    - Yarn install
  script:
    - yarn lint

Unit tests:
  stage: Build and test

  dependencies:
    - Yarn install

  script:
    - yarn test
    - mkdir public
    - cp -r coverage/lcov-report/* public/

  coverage: /All files\s*\|\s*([\d\.]+)/
  artifacts:
    paths:
      - public
    reports:
      junit: junit.xml

Build:
  stage: Build and test
  dependencies:
    - Get secrets
    - Yarn install
  script:
    - APP_LOG_LEVEL=verbose yarn build:prod

  artifacts:
    paths:
      - packages/backend/dist
      - packages/frontend/dist

Cypress:
  image: cypress/base:14.0.0
  stage: Integration test
  dependencies:
    - Get secrets
    - Yarn install
    - Build
  script:
    - echo "127.0.0.1 $SERVER_ADDRESS" >> /etc/hosts
    - cd packages/testing
    - APP_LOG_LEVEL=verbose yarn run:app & yarn test:cypress
  artifacts:
    when: always
    reports:
      junit: packages/testing/test-results.xml
    paths:
      - packages/testing/videos
      - packages/testing/screenshots

Deploy:
  environment:
    name: test
    url: http://3.233.7.98/app

  dependencies:
    - Get secrets
    - Yarn install
    - Build
  image: benwainwright/node14-with-yarn-and-aws-cli:latest
  stage: Deploy
  script:
    - yarn workspace @choirpractise/deployment cdk deploy --require-approval never
    - yarn workspace @choirpractise/deployment deploy:app

