image: node:14-stretch

stages:
  - Install
  - Build and test
  - Integration test
  - Deploy

variables:
  YARN_CACHE_FOLDER: $CI_PROJECT_DIR/.yarn/cache
  CYPRESS_CACHE_FOLDER: $CI_PROJECT_DIR/cache/Cypress

cache:
  key: ${CI_COMMIT_REF_SLUG}
  policy: pull
  paths:
    - .yarn
    - cache/Cypress
    - node_modules/
    - packages/*/node_modules
    - yarn.lock

Yarn install:
  cache:
    policy: pull-push
    key: ${CI_COMMIT_REF_SLUG}
  stage: Install
  script:
    - yarn install

Lint:
  stage: Build and test
  script:
    - yarn lint

Unit tests:
  stage: Build and test

  script:
    - yarn test
    - mkdir public
    - cp -r coverage/lcov-report/* public/

  coverage: /All files\s*\|\s*([\d\.]+)/
  artifacts:
    paths:
      - public
    reports:
      junit: junit.xml

Build:
  stage: Build and test
  script:
    - yarn build:prod

  artifacts:
    paths:
      - packages/backend/dist
      - packages/frontend/dist

Cypress:
  image: cypress/base:14.0.0
  stage: Integration test
  dependencies:
    - Build
  script:
    - cd packages/testing
    - yarn run:app & yarn test:cypress
  artifacts:
    reports:
      junit: packages/testing/test-results.xml
    paths:
      - packages/testing/videos
      - packages/testing/screenshots

Deploy:
  dependencies:
    - Build
  image: benwainwright/node14-with-yarn-and-aws-cli
  stage: Deploy
  script:
    - yarn workspace @planv7/deployment cdk deploy --require-approval never
    - yarn workspace @planv7/deployment deploy:app

