version: '3.2'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - '53:53'
      - '443:443'
      - '4566:4566'
      - '8080:8080'
    environment:
      - SERVICES=edge,s3,dynamodb,cloudformation,iam,ec2,route53,secretsmanager,cognito
      - PORT_WEB_UI=8080
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_API_KEY
    volumes:
      - './.tmp/:/tmp'
      - '/var/run/docker.sock:/var/run/docker.sock'

