# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Lint and test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.1.0
      uses: actions/setup-node@v1
      with:
        node-version: 14.1.0 
    - run: yarn install --immutable
 
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: yarn lint


  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: yarn test

  
 

  
